apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-bookstore-api
  labels:
    app: bookstore-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bookstore-api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: bookstore-api
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_session_token
        - name: AWS_REGION
          value: "us-east-1"
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    {{- if eq .Values.rolloutStrategy "canary" }}
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      {{- if .Values.analysis.enabled }}
      analysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: {{ .Release.Name }}-bookstore-api-preview
      {{- end }}
    {{- else if eq .Values.rolloutStrategy "blueGreen" }}
    blueGreen:
      activeService: {{ .Release.Name }}-bookstore-api
      previewService: {{ .Release.Name }}-bookstore-api-preview
      autoPromotionEnabled: {{ .Values.autoPromotionEnabled | default false }}
      {{- if .Values.autoPromotionEnabled }}
      autoPromotionSeconds: {{ .Values.autoPromotionSeconds | default 30 }}
      {{- end }}
      {{- if .Values.analysis.enabled }}
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: {{ .Release.Name }}-bookstore-api-preview
      {{- end }}
    {{- end }}