# Default values for the bookstore-api chart
replicaCount: 2
namespace: production
image:
  repository: ghcr.io/lalogaribo/bookstore-api
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

rolloutStrategy: "canary"

# For Blue-Green deployments
autoPromotionEnabled: false
autoPromotionSeconds: 60

# For Analysis
analysis:
  enabled: false
  prometheusAddress: "http://prometheus-server.monitoring.svc.cluster.local:9090"
