# Default values for the bookstore-api chart
replicaCount: 2

image:
  repository: ghcr.io/lalogaribo/bookstore-api
  tag: "1.0"
  pullPolicy: IfNotPresent
namespace: default
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
