name: Bookstore API CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      new_tag: ${{ steps.version_tag.outputs.new_tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repository owner
      run: |
        echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Bump version and push tag
      id: version_tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true

    - name: Build and push Docker image
      run: |
        echo "Building image with tag: ${{ steps.version_tag.outputs.new_tag }}"
        docker build -t ghcr.io/${{ env.OWNER_LC }}/preparesh-bookstore-api:${{ steps.version_tag.outputs.new_tag }} .
        docker push ghcr.io/${{ env.OWNER_LC }}/preparesh-bookstore-api:${{ steps.version_tag.outputs.new_tag }}

  Deploy:
    runs-on: self-hosted
    needs: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Set lowercase repository owner
      run: |
        echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Deploy with Helm
      run: |
        export KUBECONFIG=$HOME/.kube/config
        OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
        echo "Deploying with tag: ${{ needs.Build.outputs.new_tag }}"
        helm upgrade --install api ./helm/bookstore-api \
          --set image.repository=ghcr.io/${OWNER_LC}/preparesh-bookstore-api \
          --set image.tag=${{ needs.Build.outputs.new_tag }}
