name: Bookstore API CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repository owner
      run: |
        echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Bump Semantic Version
      id: version_tag
      uses: anothrNick/github-tag-action@v1.37.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_branches: main
        semver: true
        custom_tag: true

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ env.OWNER_LC }}/preparesh-bookstore-api:${{ steps.version_tag.new_tag }} .
        docker push ghcr.io/${{ env.OWNER_LC }}/preparesh-bookstore-api:${{ steps.version_tag.new_tag }}

  Deploy:
    runs-on: self-hosted
    needs: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Set lowercase repository owner
      run: |
        echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Deploy with Helm
      run: |
        export KUBECONFIG=$HOME/.kube/config
        TAG=$(git rev-parse --short HEAD)
        OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
        helm upgrade --install api ./helm/bookstore-api \
          --set image.repository=ghcr.io/${OWNER_LC}/preparesh-bookstore-api \
          --set image.tag=${{ steps.version_tag.new_tag }}
    # - name: Deploy with Helm
    #   run: |
    #     helm upgrade --install api ./helm --set image.repository=ghcr.io/${{ env.OWNER_LC }}/preparesh-bookstore-api --set image.tag=$TAG
